title: "Datavillage Technical Documentation"
logo: "/assets/images/datavillage-logo.png"
remote_theme: just-the-docs/just-the-docs
search_enabled: true
# For localhost, uncomment following line
#theme: just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Go to the Data Collaboration Platform":
    - "https://www.datavillage.me/console"

aux_links_new_tab: true
