site_name: Documentation
nav:
    - Home: index.md
    - Getting Started:
      - What is Datavillage?: 20-getting-started/01-what-is-datavillage.md
      - How Datavillage Works: 20-getting-started/02-how-it-works.md
      - Setup a Collaboration: 20-getting-started/03-create-space.md
      - Run a Collaboration: 20-collaboration-setup/01-create-space.md
      - Testing and Debugging: 20-collaboration-setup/01-create-space.md
    - Data Connectors:
      - For Enterprise Data: 20-collaboration-setup/01-create-space.md
      - For Personal Data: 20-collaboration-setup/02-invite.md
      - Custom API's: 20-collaboration-setup/02-invite.md
    - Algorithm Models: 10-getting-started.md
    - Security & Confidentiality: 10-getting-started.md
    - Services:
      - Authorization: 20-collaboration-setup/01-create-space.md
      - Logging & Monitoring: 20-collaboration-setup/02-invite.md
      - Audit: 20-collaboration-setup/03-datasets.md
    - API reference: 10-getting-started.md
    - Partners:
      - For Data Providers: 20-collaboration-setup/01-create-space.md
      - For Algorithm Providers: 20-collaboration-setup/02-invite.md


theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/datavillage-logo-icon.png
  features:
    - toc.follow
    - navigation.footer
    - navigation.path
    - navigation.top
  custom_dir: custom_theme/
  palette:
    primary: custom
    accent: custom
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

use_directory_urls: false

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - attr_list 
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/datavillage-me
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datavillage
   

copyright: Copyright &copy; Datavillage 2023

plugins:
  - awesome-pages
  - search
      #order_by: filename   ## do not use this - mkdocs sorts alphanumerically by default anyway, and forcing this, causes the index.md file to be mis-sorted